env:
  - GO111MODULE=on
  - CGO_ENABLED=0

before:
  hooks:
    - go mod tidy
    - go generate ./...
builds:
  - id: edge 
    binary: edge-{{ .Arch }}
    main: ./edge.go
    goos:
      - linux
      - windows
      - darwin

  - id: http 
    binary: http-{{ .Arch }}
    main: ./http.go
    goos:
      - linux
      - windows
      - darwin

archives:
  - replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ incpatch .Version }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
